version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 7000:5432
    environment:
      POSTGRES_USER: wango
      POSTGRES_PASSWORD: 111
      POSTGRES_DB: wangodb
    container_name: wango-db
